name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    attributes:
      label: Have you tried the latest build?
      description: Please [download the latest development build](https://gyroflow.xyz/devbuild/) to see if the issue still persists.
      options:
      - label: I have tried the latest build
        required: true
  - type: checkboxes
    attributes:
      label: Do you have latest GPU drivers installed?
      description: Make sure to download and install latest drivers for your GPU from manufacturer's website (eg. NVIDIA, AMD or Intel). Drivers installed by the system are not enough.
      options:
      - label: I have the latest GPU drivers installed, I'm absolutely sure.
        required: true
  - type: checkboxes
    attributes:
      label: Have you checked the documentation?
      description: Make sure to check the [FAQ](https://docs.gyroflow.xyz/app/getting-started/faq) and [Troubleshooting](https://docs.gyroflow.xyz/app/getting-started/troubleshooting) pages before reporting a bug report
      options:
      - label: I have read the FAQ and Troubleshooting and didn't find my issue there.
        required: true
  - type: input
    id: gyroflow-version
    attributes:
      label: Gyroflow version
      description: What version of Gyroflow are you running?
      placeholder: Version nr or commit id
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      description: Please be specific, for example "macOS Catalina 10.15.4"
      placeholder: OS and version nr
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: What GPU are you using?
      description: If you are using a GPU please tell us what model you have.
      placeholder: Brand and model
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please try to run Gyroflow via terminal and paste any relevant log output here. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: "### Please share any relevant files"
  - type: markdown
    attributes:
      value: |
        This can be motion data files, video files, screenshots etc. Smaller files can be zipped and uploaded here. Larger files can be shared using Google Drive, Dropbox, WeTransfer, mega.nz, or similar.